
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/example
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:example}
  flyway:
    baseline-on-migrate: true


mybatis:
  project: src/main/java
  resources: src/main/resources
  mapper-locations: classpath*:mappers/*Mapper.xml
  type-aliases-package: com.example.demo.model
